# Generated by Django 5.0.1 on 2024-02-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0002_remove_user_company_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Время транзакции')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('ch', 'Pay to cash'), ('cd', 'Pay to card')], max_length=50, verbose_name='Способ оплаты')),
                ('purchased_course', models.ManyToManyField(to='lms.course', verbose_name='Купленные курсы')),
                ('purchased_lessons', models.ManyToManyField(to='lms.lesson', verbose_name='Купленные отдельные уроки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь совершивший транзакцию')),
            ],
        ),
    ]
