# Generated by Django 5.0.1 on 2024-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0003_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchased_course',
            field=models.ManyToManyField(blank=True, null=True, to='lms.course', verbose_name='Купленные курсы'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchased_lessons',
            field=models.ManyToManyField(blank=True, null=True, to='lms.lesson', verbose_name='Купленные отдельные уроки'),
        ),
    ]
