# Generated by Django 5.0.1 on 2024-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_is_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_email',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchased_course',
            field=models.ManyToManyField(blank=True, to='lms.course', verbose_name='Купленные курсы'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchased_lessons',
            field=models.ManyToManyField(blank=True, to='lms.lesson', verbose_name='Купленные отдельные уроки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Личная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
