# Generated by Django 5.0.1 on 2024-03-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_lesson_video_url'),
        ('users', '0008_remove_subscribe_user_subscribe_proprietor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='courses',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курс на которые подписан'),
        ),
    ]
