# Generated by Django 5.0.1 on 2024-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_subscribe_courses_subscribe_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
    ]
