# Generated by Django 5.0.1 on 2024-03-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_transaction_strip_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purchased_lessons',
        ),
    ]
