# Generated by Django 5.0.1 on 2024-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_transaction_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='strip_session_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='идентификатор сессии'),
        ),
    ]
