# Generated by Django 5.0.1 on 2024-03-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_transaction_strip_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='url_to_pay',
            field=models.URLField(default='', verbose_name='Ссылка на оплату'),
        ),
    ]
