# Generated by Django 5.0.1 on 2024-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('preview', models.ImageField(upload_to='lesson/', verbose_name='Превью')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('preview', models.ImageField(upload_to='course/')),
                ('lessons', models.ManyToManyField(to='lms.lesson', verbose_name='Уроки курса')),
            ],
        ),
    ]
