# Generated by Django 5.0.1 on 2024-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_course_proprietor_lesson_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
