# Generated by Django 5.0.1 on 2024-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_course_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, to='lms.lesson', verbose_name='Уроки курса'),
        ),
    ]
